blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Feature Requests & Questions
    url: https://discord.gg/shfBFeczrm
    about: Please ask and answer questions here.
  - name: ğŸ¥ Twitter
    url: https://twitter.com/stijnvanhulle
    about: Ask questions around Kubb on Twitter